name: Build Vendor
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, gd, pdo_mysql
          tools: composer

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction

      - name: Upload Vendor
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor/